// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseContainer: typeof import('./src/components/Containers/BaseContainer.vue')['default']
    Box: typeof import('./src/components/Box/Box.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElTimeSelect: typeof import('element-plus/es')['ElTimeSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    InfoBox: typeof import('./src/components/Box/InfoBox.vue')['default']
    Map: typeof import('./src/components/Map/Map.vue')['default']
    NavMenu: typeof import('./src/components/Nav/NavMenu.vue')['default']
    ParkingTicketBox: typeof import('./src/components/ParkingTicket/ParkingTicketBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TBadge: typeof import('./src/components/Common/TBadge/TBadge.vue')['default']
    TButton: typeof import('./src/components/Controls/Button/TButton.vue')['default']
    TInput: typeof import('./src/components/Controls/Input/TInput.vue')['default']
    TInputLeftSide: typeof import('./src/components/Controls/Input/Partials/Sides/Left/TInputLeftSide.vue')['default']
    TInputLeftSideText: typeof import('./src/components/Controls/Input/Partials/Sides/Left/TInputLeftSideText.vue')['default']
  }
}
